### PR TITLE
Fix #160 Fab Image isn't tinted correctly

### PR DESCRIPTION
**Pull request by S-H-Y-A**
### First time contributor checklist

- [x] I have read [how to contribute](/.github/CONTRIBUTING.md) to this project
- [x] I have read [the code of conduct](/.github/CODE_OF_CONDUCT.md) to this project

### Contributor checklist

- [x] I am using the provided [codeStyleConfig.xml](/.idea/codeStyles)
- [x] I have tested my contribution on these devices:
 * Virtual Nexus 5, Android 5.0~8.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit 
      using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-using-keywords/)

----------

### Description

[Fix the bug #160](https://github.com/leinardi/FloatingActionButtonSpeedDial/pull/162#issuecomment-803540705)

### CODE REVIEW

**Comment by leinardi** [comment]
Please target the `master` branch.

**Comment by S-H-Y-A** [comment]
Sorry to bother you over and over.

**Comment by leinardi** [comment]
No worries, I should have added the `master` branch check to the contributor checklist.

Anyway, I tried the PR and I unfortunately still have the same issue with the icon color on API 23 (screenshot on the right):

image

I did some testing and the issue started with this comming: a4ce4bd7c729a1a9dfed5b6be0f11ae77011c99b (btw, I didn't notice during the original PR: please always write a descriptive commit message or amend the previous commit, if the previous commit message still fits).

**Comment by leinardi** [comment]
Also, please remember to rebase on the latest `master` branch because I think there are conflicts.

**Comment by S-H-Y-A** [comment]
This app is working correctly on My API 23 AVD.
スクリーンショット 2021-03-23 183344

**Comment by leinardi** [comment]
Oh sorry! You are right! I messed up when checking out the branch because of the conflicts with master.
Speaking of it, I can't merge it until those are solved:
image

Could you please rebase on top of the latest `master`? As soon as it is rebased, I'll merge the MR, thanks a lot for the new features and fixes :+1:

**Comment by leinardi** [comment]
Thanks! Merged :)

**Pull request merged**
