### PR TITLE
Fix #79: Doesn't change label text language when app language is chan…

### LINKED ISSUE #79: Doesn't change label text language when app language is changed dynamically
I have noticed a bug in this library which makes the label text doesn't change the label text to the current locale if the app language is changed dynamically.(even if referenced from strings.xml)

however,the floating menus correctly change the test label after the next restart of the app.

please fix this

### PR DESCRIPTION
**Pull request by leinardi**

### CODE REVIEW

**Comment by ashif-ismail** [comment]
has this change merged to stable release ?

**Comment by leinardi** [comment]
Hi @SheikhZayed, it has been merged to master branch, but is not released yet.

**Comment by ashif-ismail** [comment]
Can expect soon,?

**Comment by leinardi** [comment]
I would like to wait for more changes before releasing v2 so, I don't think it will be released any time soon.

**Pull request merged**
